name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run test
      run: make tests

    - name: Install RPM packages
      run: sudo dnf install git sed

    - name: Create package
      run: make package
