name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run test
      run: make tests

    - name: Create Debian package
      run: make deb-package

    - name: Create and fill artifact downloads folder
      run: |
        mkdir downloads
        mv unseq.deb downloads

    - name: Use Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with:
        name: assets-for-downloads
        path: downloads
